name: cof
channels:
  - defaults
  - astropy
  - conda-forge
dependencies:
  - python>=3.5
  - astroalign
  - astromatic-source-extractor
  - astromatic-psfex
  - astrometry
  - astropy
  - astroquery
  - ccdproc
  - cmasher
#  - libgsl>=2.7
  - matplotlib
  - numpy
  - photutils
  - PyYAML
  - reproject
  - requests
  - sep
#  - setuptools
  - tqdm