name: craft-optical-followup
channels:
  - defaults
  - astropy
  - conda-forge
dependencies:
  - python>=3.5
  - astroalign>=2.4
  - astromatic-source-extractor
  - astrometry>0.92
  - astropy>=5.0
  - astroquery>=0.4
  - ccdproc>=2.3
  - cmasher>=1.6
  - libgsl>=2.7
  - matplotlib>=3.0
  - numpy=1.23
  - photutils>=1.5
  - PyYAML>=5.3
  - reproject>=0.9.1
  - requests
  - sep>=1.0
  - setuptools>=65.0
  - tqdm