#[build-system]
#requires = ["flit_core >=3.2,<4"]
#build-backend = "flit_core.buildapi"

[project]
name = "craft-optical-followup"
authors = [{name = "Lachlan Marnoch", email = "lachlan.marnoch@gmail.com"}]
version = "0.9.0"